version: "3"

services:
  gateway: 
    container_name: nnnco-gateway
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    ports:
      - 8080:80
  api:
    build: ./packages/api
    container_name: nnnco-api
    ports: 
      - 3001:3001
    environment:
      - PORT=3001